using System.Collections.Generic;

namespace Seedforger {

  /// <summary>
  /// Built-in client fingerprints. Transcribed one-for-one from the historical
  /// switch in <see cref="TorrentClientFactory"/>, plus a set of modern clients.
  /// Values not explicitly set fall back to the model defaults, which match the
  /// TorrentClient constructor defaults (DefNumWant=200, StartOffset=10000000,
  /// MaxOffset=25000000, Parse=false, SearchString="", ProcessName="").
  /// </summary>
  public static class DefaultClientProfiles {
    public static IReadOnlyList<ClientProfile> All { get; } = new List<ClientProfile> {

      // ===================== qBittorrent (modern) =====================
      new ClientProfile {
        Family = "qBittorrent", Version = "5.2.3",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-qB5230-",
        PeerIdRandom = new IdSpec { Type = "random", Length = 12, UrlEncode = true, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: qBittorrent/5.2.3\r\nAccept-Encoding: gzip\r\nConnection: close\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&corrupt=0&key={key}{event}&numwant={numwant}&compact=1&no_peer_id=1&supportcrypto=1&redundant=0",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-qB5230-", ProcessName = "qbittorrent",
        StartOffset = 0, MaxOffset = 200000000,
      },
      new ClientProfile {
        Family = "qBittorrent", Version = "4.6.7",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-qB4670-",
        PeerIdRandom = new IdSpec { Type = "random", Length = 12, UrlEncode = true, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: qBittorrent/4.6.7\r\nAccept-Encoding: gzip\r\nConnection: close\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&corrupt=0&key={key}{event}&numwant={numwant}&compact=1&no_peer_id=1&supportcrypto=1&redundant=0",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-qB4670-", ProcessName = "qbittorrent",
        StartOffset = 0, MaxOffset = 200000000,
      },

      // ===================== uTorrent =====================
      new ClientProfile {
        Family = "uTorrent", Version = "3.3.2",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-UT3320-%18w",
        PeerIdRandom = new IdSpec { Type = "random", Length = 10, UrlEncode = true, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: uTorrent/3320\r\nAccept-Encoding: gzip\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&corrupt=0&key={key}{event}&numwant={numwant}&compact=1&no_peer_id=1",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-UT3320-", ProcessName = "uTorrent",
        StartOffset = 0, MaxOffset = 200000000,
      },
      new ClientProfile {
        Family = "uTorrent", Version = "3.3.0",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-UT3300-%b9s",
        PeerIdRandom = new IdSpec { Type = "random", Length = 10, UrlEncode = true, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: uTorrent/3300\r\nAccept-Encoding: gzip\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&corrupt=0&key={key}{event}&numwant={numwant}&compact=1&no_peer_id=1",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-UT3300-", ProcessName = "uTorrent",
        StartOffset = 0, MaxOffset = 200000000,
      },
      new ClientProfile {
        Family = "uTorrent", Version = "3.2.0",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-UT3200-z8\0.",
        PeerIdRandom = new IdSpec { Type = "random", Length = 10, UrlEncode = true, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: uTorrent/3200\r\nAccept-Encoding: gzip\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&corrupt=0&key={key}{event}&numwant={numwant}&compact=1&no_peer_id=1",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-UT3200-", ProcessName = "uTorrent",
        StartOffset = 0, MaxOffset = 60000000,
      },
      new ClientProfile {
        Family = "uTorrent", Version = "2.0.1 (build 19078)",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-UT2010-%86J",
        PeerIdRandom = new IdSpec { Type = "random", Length = 10, UrlEncode = true, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: uTorrent/2010(19078)\r\nAccept-Encoding: gzip\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&corrupt=0&key={key}{event}&numwant={numwant}&compact=1&no_peer_id=1",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-UT2010-", ProcessName = "uTorrent",
        StartOffset = 0, MaxOffset = 60000000,
      },
      new ClientProfile {
        Family = "uTorrent", Version = "1.8.5 (build 17414)",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-UT1850-%06D",
        PeerIdRandom = new IdSpec { Type = "random", Length = 10, UrlEncode = true, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: uTorrent/1850(17414)\r\nAccept-Encoding: gzip\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&corrupt=0&key={key}{event}&numwant={numwant}&compact=1&no_peer_id=1",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-UT1850-", ProcessName = "uTorrent",
        StartOffset = 0, MaxOffset = 60000000,
      },
      new ClientProfile {
        Family = "uTorrent", Version = "1.8.2",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-UT1820-%06D",
        PeerIdRandom = new IdSpec { Type = "random", Length = 10, UrlEncode = true, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: uTorrent/1820(15357)\r\nAccept-Encoding: gzip\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&corrupt=0&key={key}{event}&numwant={numwant}&compact=1&no_peer_id=1",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=%.20U", ProcessName = "uTorrent",
        StartOffset = 0, MaxOffset = 60000000,
      },
      new ClientProfile {
        Family = "uTorrent", Version = "1.8.1-beta(11903)",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-UT181B-%7f.",
        PeerIdRandom = new IdSpec { Type = "random", Length = 10, UrlEncode = true, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: uTorrent/181B(11903)\r\nAccept-Encoding: gzip\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&corrupt=0&key={key}{event}&numwant={numwant}&compact=1&no_peer_id=1",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-UT181B-", ProcessName = "uTorrent",
        StartOffset = 0, MaxOffset = 60000000,
      },
      new ClientProfile {
        Family = "uTorrent", Version = "1.8.0",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-UT1800-%25.",
        PeerIdRandom = new IdSpec { Type = "random", Length = 10, UrlEncode = true, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: uTorrent/1800\r\nAccept-Encoding: gzip\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&corrupt=0&key={key}{event}&numwant={numwant}&compact=1&no_peer_id=1",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-UT1800-", ProcessName = "uTorrent",
        StartOffset = 0, MaxOffset = 60000000,
      },
      new ClientProfile {
        Family = "uTorrent", Version = "1.7.7",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-UT1770-%f3%9f",
        PeerIdRandom = new IdSpec { Type = "random", Length = 10, UrlEncode = true, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: uTorrent/1770\r\nAccept-Encoding: gzip\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&key={key}{event}&numwant={numwant}&compact=1&no_peer_id=1",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-UT1770-", ProcessName = "uTorrent",
        StartOffset = 0, MaxOffset = 60000000,
      },
      new ClientProfile {
        Family = "uTorrent", Version = "1.7.6",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-UT1760-%b3%9e",
        PeerIdRandom = new IdSpec { Type = "random", Length = 10, UrlEncode = true, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: uTorrent/1760\r\nAccept-Encoding: gzip\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&key={key}{event}&numwant={numwant}&compact=1&no_peer_id=1",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-UT1760-", ProcessName = "uTorrent",
        StartOffset = 0, MaxOffset = 60000000,
      },
      new ClientProfile {
        Family = "uTorrent", Version = "1.7.5",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-UT1750-%fa%91",
        PeerIdRandom = new IdSpec { Type = "random", Length = 10, UrlEncode = true, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: uTorrent/1750\r\nAccept-Encoding: gzip\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&key={key}{event}&numwant={numwant}&compact=1&no_peer_id=1",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-UT1750-", ProcessName = "uTorrent",
        StartOffset = 0, MaxOffset = 60000000,
      },
      new ClientProfile {
        Family = "uTorrent", Version = "1.6.1",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-UT1610-%ea%81",
        PeerIdRandom = new IdSpec { Type = "random", Length = 10, UrlEncode = true, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: uTorrent/1610\r\nAccept-Encoding: gzip\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&key={key}{event}&numwant={numwant}&compact=1&no_peer_id=1",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-UT1610-", ProcessName = "uTorrent",
        StartOffset = 0, MaxOffset = 60000000,
      },
      new ClientProfile {
        Family = "uTorrent", Version = "1.6",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-UT1600-%d9%81",
        PeerIdRandom = new IdSpec { Type = "random", Length = 10, UrlEncode = true, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: uTorrent/1600\r\nAccept-Encoding: gzip\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&key={key}{event}&numwant={numwant}&compact=1&no_peer_id=1",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-UT1600-", ProcessName = "uTorrent",
        StartOffset = 0, MaxOffset = 60000000,
      },

      // ===================== BitComet =====================
      new ClientProfile {
        Family = "BitComet", Version = "1.20",
        HttpProtocol = "HTTP/1.1", HashUpperCase = true,
        Key = new IdSpec { Type = "numeric", Length = 5, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "-BC0120-",
        PeerIdRandom = new IdSpec { Type = "random", Length = 12, UrlEncode = true, UpperCase = true },
        Headers = "Host: {host}\r\nConnection: close\r\nAccpet: */*\r\nAccept-Encoding: gzip\r\nUser-Agent: BitComet/1.20.3.25\r\nPragma: no-cache\r\nCache-Control: no-cache\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&natmapped=1&localip={localip}&port_type=wan&uploaded={uploaded}&downloaded={downloaded}&left={left}&numwant={numwant}&compact=1&no_peer_id=1&key={key}{event}",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-BC0120-", ProcessName = "BitComet",
        StartOffset = 0, MaxOffset = 60000000,
      },
      new ClientProfile {
        Family = "BitComet", Version = "1.03",
        HttpProtocol = "HTTP/1.1", HashUpperCase = true,
        Key = new IdSpec { Type = "numeric", Length = 5, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "-BC0103-",
        PeerIdRandom = new IdSpec { Type = "random", Length = 12, UrlEncode = true, UpperCase = true },
        Headers = "Host: {host}\r\nConnection: close\r\nAccpet: */*\r\nAccept-Encoding: gzip\r\nUser-Agent: BitComet/1.3.7.17\r\nPragma: no-cache\r\nCache-Control: no-cache\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&natmapped=1&localip={localip}&port_type=wan&uploaded={uploaded}&downloaded={downloaded}&left={left}&numwant={numwant}&compact=1&no_peer_id=1&key={key}{event}",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-BC0103-", ProcessName = "BitComet",
        StartOffset = 0, MaxOffset = 60000000,
      },
      new ClientProfile {
        Family = "BitComet", Version = "0.98",
        HttpProtocol = "HTTP/1.1", HashUpperCase = true,
        Key = new IdSpec { Type = "numeric", Length = 5, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "-BC0098-",
        PeerIdRandom = new IdSpec { Type = "random", Length = 12, UrlEncode = true, UpperCase = true },
        Headers = "Accept: */*\r\nAccept-Encoding: gzip\r\nConnection: close\r\nHost: {host}\r\nUser-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; .NET CLR 1.1.4322)\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&natmapped=1&localip={localip}&port_type=wan&uploaded={uploaded}&downloaded={downloaded}&left={left}&numwant={numwant}&compact=1&no_peer_id=1&key={key}{event}",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-BC0098-", ProcessName = "BitComet",
        StartOffset = 0, MaxOffset = 60000000,
      },
      new ClientProfile {
        Family = "BitComet", Version = "0.96",
        HttpProtocol = "HTTP/1.1", HashUpperCase = true,
        Key = new IdSpec { Type = "numeric", Length = 5, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "-BC0096-",
        PeerIdRandom = new IdSpec { Type = "random", Length = 12, UrlEncode = true, UpperCase = true },
        Headers = "Accept: */*\r\nAccept-Encoding: gzip\r\nConnection: close\r\nHost: {host}\r\nUser-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; .NET CLR 1.1.4322)\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&natmapped=1&localip={localip}&port_type=wan&uploaded={uploaded}&downloaded={downloaded}&left={left}&numwant={numwant}&compact=1&no_peer_id=1&key={key}{event}",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-BC0096-", ProcessName = "BitComet",
        StartOffset = 0, MaxOffset = 60000000,
      },
      new ClientProfile {
        Family = "BitComet", Version = "0.93",
        HttpProtocol = "HTTP/1.1", HashUpperCase = true,
        Key = new IdSpec { Type = "numeric", Length = 5, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "-BC0093-",
        PeerIdRandom = new IdSpec { Type = "random", Length = 12, UrlEncode = true, UpperCase = true },
        Headers = "Accept: */*\r\nAccept-Encoding: gzip\r\nConnection: close\r\nHost: {host}\r\nUser-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; .NET CLR 1.1.4322)\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&natmapped=1&localip={localip}&port_type=wan&uploaded={uploaded}&downloaded={downloaded}&left={left}&numwant={numwant}&compact=1&no_peer_id=1&key={key}{event}",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-BC0093-", ProcessName = "BitComet",
        StartOffset = 0, MaxOffset = 60000000,
      },
      new ClientProfile {
        Family = "BitComet", Version = "0.92",
        HttpProtocol = "HTTP/1.1", HashUpperCase = true,
        Key = new IdSpec { Type = "numeric", Length = 5, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "-BC0092-",
        PeerIdRandom = new IdSpec { Type = "random", Length = 12, UrlEncode = true, UpperCase = true },
        Headers = "Accept: */*\r\nAccept-Encoding: gzip\r\nConnection: close\r\nHost: {host}\r\nUser-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; .NET CLR 1.1.4322)\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&natmapped=1&localip={localip}&port_type=wan&uploaded={uploaded}&downloaded={downloaded}&left={left}&numwant={numwant}&compact=1&no_peer_id=1&key={key}{event}",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-BC0092-", ProcessName = "BitComet",
        StartOffset = 0, MaxOffset = 60000000,
      },

      // ===================== Azureus =====================
      new ClientProfile {
        Family = "Azureus", Version = "3.1.1.0",
        HttpProtocol = "HTTP/1.1", HashUpperCase = true,
        Key = new IdSpec { Type = "alphanumeric", Length = 8, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "-AZ3110-",
        PeerIdRandom = new IdSpec { Type = "alphanumeric", Length = 12, UrlEncode = false, UpperCase = false },
        Headers = "User-Agent: Azureus 3.1.1.0;Windows XP;Java 1.6.0_07\r\nConnection: close\r\nAccept-Encoding: gzip\r\nHost: {host}\r\nAccept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&supportcrypto=1&port={port}&azudp={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&corrupt=0{event}&numwant={numwant}&no_peer_id=1&compact=1&key={key}&azver=3",
        DefNumWant = 50, Parse = true, SearchString = "&peer_id=-AZ3110-", ProcessName = "Azureus",
        StartOffset = 0, MaxOffset = 100000000,
      },
      new ClientProfile {
        Family = "Azureus", Version = "3.0.5.0",
        HttpProtocol = "HTTP/1.1", HashUpperCase = true,
        Key = new IdSpec { Type = "alphanumeric", Length = 8, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "-AZ3050-",
        PeerIdRandom = new IdSpec { Type = "alphanumeric", Length = 12, UrlEncode = false, UpperCase = false },
        Headers = "User-Agent: Azureus 3.0.5.0;Windows XP;Java 1.6.0_05\r\nConnection: close\r\nAccept-Encoding: gzip\r\nHost: {host}\r\nAccept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2\r\nContent-type: application/x-www-form-urlencoded\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&supportcrypto=1&port={port}&azudp={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&corrupt=0{event}&numwant={numwant}&no_peer_id=1&compact=1&key={key}&azver=3",
        DefNumWant = 50, Parse = true, SearchString = "&peer_id=-AZ3050-", ProcessName = "Azureus",
        StartOffset = 0, MaxOffset = 100000000,
      },
      new ClientProfile {
        Family = "Azureus", Version = "3.0.4.2",
        HttpProtocol = "HTTP/1.1", HashUpperCase = true,
        Key = new IdSpec { Type = "alphanumeric", Length = 8, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "-AZ3042-",
        PeerIdRandom = new IdSpec { Type = "alphanumeric", Length = 12, UrlEncode = false, UpperCase = false },
        Headers = "User-Agent: Azureus 3.0.4.2;Windows XP;Java 1.5.0_07\r\nConnection: close\r\nAccept-Encoding: gzip\r\nHost: {host}\r\nAccept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2\r\nContent-type: application/x-www-form-urlencoded\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&supportcrypto=1&port={port}&azudp={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&corrupt=0{event}&numwant={numwant}&no_peer_id=1&compact=1&key={key}&azver=3",
        DefNumWant = 50, Parse = true, SearchString = "&peer_id=-AZ3042-", ProcessName = "Azureus",
        StartOffset = 0, MaxOffset = 100000000,
      },
      new ClientProfile {
        Family = "Azureus", Version = "3.0.3.4",
        HttpProtocol = "HTTP/1.1", HashUpperCase = true,
        Key = new IdSpec { Type = "alphanumeric", Length = 8, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "-AZ3034-",
        PeerIdRandom = new IdSpec { Type = "alphanumeric", Length = 12, UrlEncode = false, UpperCase = false },
        Headers = "User-Agent: Azureus 3.0.3.4;Windows XP;Java 1.6.0_03\r\nConnection: close\r\nAccept-Encoding: gzip\r\nHost: {host}\r\nAccept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&supportcrypto=1&port={port}&azudp={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&corrupt=0{event}&numwant={numwant}&no_peer_id=1&compact=1&key={key}&azver=3",
        DefNumWant = 50, Parse = true, SearchString = "&peer_id=-AZ3034-", ProcessName = "Azureus",
        StartOffset = 0, MaxOffset = 100000000,
      },
      new ClientProfile {
        Family = "Azureus", Version = "3.0.2.2",
        HttpProtocol = "HTTP/1.1", HashUpperCase = true,
        Key = new IdSpec { Type = "alphanumeric", Length = 8, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "-AZ3022-",
        PeerIdRandom = new IdSpec { Type = "alphanumeric", Length = 12, UrlEncode = false, UpperCase = false },
        Headers = "User-Agent: Azureus 3.0.2.2;Windows XP;Java 1.6.0_01\r\nConnection: close\r\nAccept-Encoding: gzip\r\nHost: {host}\r\nAccept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&supportcrypto=1&port={port}&azudp={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&corrupt=0{event}&numwant={numwant}&no_peer_id=1&compact=1&key={key}&azver=3",
        DefNumWant = 50, Parse = true, SearchString = "&peer_id=-AZ3022-", ProcessName = "Azureus",
        StartOffset = 0, MaxOffset = 100000000,
      },
      new ClientProfile {
        Family = "Azureus", Version = "2.5.0.4",
        HttpProtocol = "HTTP/1.1", HashUpperCase = true,
        Key = new IdSpec { Type = "alphanumeric", Length = 8, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "-AZ2504-",
        PeerIdRandom = new IdSpec { Type = "alphanumeric", Length = 12, UrlEncode = false, UpperCase = false },
        Headers = "User-Agent: Azureus 2.5.0.4;Windows XP;Java 1.5.0_10\r\nConnection: close\r\nAccept-Encoding: gzip\r\nHost: {host}\r\nAccept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2\r\nContent-type: application/x-www-form-urlencoded\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&supportcrypto=1&port={port}&azudp={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}{event}&numwant={numwant}&no_peer_id=1&compact=1&key={key}&azver=3",
        DefNumWant = 50, Parse = true, SearchString = "&peer_id=-AZ2504-", ProcessName = "Azureus",
        StartOffset = 0, MaxOffset = 100000000,
      },

      // ===================== Vuze =====================
      new ClientProfile {
        Family = "Vuze", Version = "4.2.0.8",
        HttpProtocol = "HTTP/1.1", HashUpperCase = true,
        Key = new IdSpec { Type = "alphanumeric", Length = 8, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "-AZ4208-",
        PeerIdRandom = new IdSpec { Type = "alphanumeric", Length = 12, UrlEncode = false, UpperCase = false },
        Headers = "User-Agent: Azureus 4.2.0.8;Windows XP;Java 1.6.0_05\r\nConnection: close\r\nAccept-Encoding: gzip\r\nHost: {host}\r\nAccept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&supportcrypto=1&port={port}&azudp={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&corrupt=0{event}&numwant={numwant}&no_peer_id=1&compact=1&key={key}&azver=3",
        DefNumWant = 50, Parse = true, SearchString = "&peer_id=-AZ4208-", ProcessName = "azureus",
        StartOffset = 0, MaxOffset = 100000000,
      },

      // ===================== BitTorrent =====================
      new ClientProfile {
        Family = "BitTorrent", Version = "6.0.3 (8642)",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "M6-0-3--",
        PeerIdRandom = new IdSpec { Type = "random", Length = 12, UrlEncode = true, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: BitTorrent/6030\r\nAccept-Encoding: gzip\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&key={key}{event}&numwant={numwant}&compact=1&no_peer_id=1",
        DefNumWant = 200, Parse = false, SearchString = "", ProcessName = "bittorrent",
        StartOffset = 0, MaxOffset = 100000000,
      },

      // ===================== Transmission =====================
      new ClientProfile {
        Family = "Transmission", Version = "4.1.3",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-TR4130-",
        PeerIdRandom = new IdSpec { Type = "alphanumeric", Length = 12, UrlEncode = false, UpperCase = false },
        Headers = "User-Agent: Transmission/4.1.3\r\nHost: {host}\r\nAccept: */*\r\nAccept-Encoding: gzip;q=1.0, deflate, identity\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&numwant={numwant}&key={key}&compact=1&supportcrypto=1{event}",
        DefNumWant = 80, Parse = true, SearchString = "&peer_id=-TR4130-", ProcessName = "transmission",
        StartOffset = 0, MaxOffset = 200000000,
      },
      new ClientProfile {
        Family = "Transmission", Version = "2.92 (14714)",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-TR2920-",
        PeerIdRandom = new IdSpec { Type = "alphanumeric", Length = 12, UrlEncode = false, UpperCase = false },
        Headers = "User-Agent: Transmission/2.92\r\nHost: {host}\r\nAccept: */*\r\nAccept-Encoding: gzip;q=1.0, deflate, identity\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&numwant={numwant}&key={key}&compact=1&supportcrypto=1{event}",
        DefNumWant = 80, Parse = false, SearchString = "&peer_id=-TR2920-", ProcessName = "Transmission",
        StartOffset = 10000000, MaxOffset = 25000000,
      },
      new ClientProfile {
        Family = "Transmission", Version = "2.82 (14160)",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-TR2500-",
        PeerIdRandom = new IdSpec { Type = "alphanumeric", Length = 12, UrlEncode = false, UpperCase = false },
        Headers = "User-Agent: Transmission/2.82\r\nHost: {host}\r\nAccept: */*\r\nAccept-Encoding: gzip;q=1.0, deflate, identity\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&numwant={numwant}&key={key}&compact=1&supportcrypto=1{event}",
        DefNumWant = 80, Parse = false, SearchString = "&peer_id=-TR2500-", ProcessName = "Transmission",
        StartOffset = 10000000, MaxOffset = 25000000,
      },

      // ===================== ABC =====================
      new ClientProfile {
        Family = "ABC", Version = "3.1",
        HttpProtocol = "HTTP/1.1", HashUpperCase = true,
        Key = new IdSpec { Type = "alphanumeric", Length = 6, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "A310--",
        PeerIdRandom = new IdSpec { Type = "alphanumeric", Length = 14, UrlEncode = false, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: ABC/ABC-3.1.0\r\nAccept-Encoding: gzip\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&trackerid=48&no_peer_id=1&compact=1{event}&key={key}",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=A310--", ProcessName = "abc",
        StartOffset = 10000000, MaxOffset = 25000000,
      },

      // ===================== BitLord =====================
      new ClientProfile {
        Family = "BitLord", Version = "1.1",
        HttpProtocol = "HTTP/1.0", HashUpperCase = true,
        Key = new IdSpec { Type = "numeric", Length = 4, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "exbc%01%01LORDCz%03%92",
        PeerIdRandom = new IdSpec { Type = "random", Length = 6, UrlEncode = true, UpperCase = true },
        Headers = "User-Agent: BitTorrent/3.4.2\r\nConnection: close\r\nAccept-Encoding: gzip, deflate\r\nHost: {host}\r\nCache-Control: no-cache\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&natmapped=1&uploaded={uploaded}&downloaded={downloaded}&left={left}&numwant=200&compact=1&no_peer_id=1&key={key}{event}",
        DefNumWant = 200, Parse = false, SearchString = "", ProcessName = "",
        StartOffset = 10000000, MaxOffset = 25000000,
      },

      // ===================== BTuga =====================
      new ClientProfile {
        Family = "BTuga", Version = "2.1.8",
        HttpProtocol = "HTTP/1.1", HashUpperCase = true,
        Key = new IdSpec { Type = "alphanumeric", Length = 6, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "R26---",
        PeerIdRandom = new IdSpec { Type = "alphanumeric", Length = 14, UrlEncode = false, UpperCase = false },
        Headers = "Host: {host}\r\nAccept-Encoding: gzip\r\nUser-Agent: BTuga/Revolution-2.6\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&no_peer_id=1&compact=1{event}&key={key}",
        DefNumWant = 200, Parse = false, SearchString = "", ProcessName = "",
        StartOffset = 10000000, MaxOffset = 25000000,
      },

      // ===================== BitTornado =====================
      new ClientProfile {
        Family = "BitTornado", Version = "0.3.17",
        HttpProtocol = "HTTP/1.1", HashUpperCase = true,
        Key = new IdSpec { Type = "alphanumeric", Length = 6, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "T03H-----",
        PeerIdRandom = new IdSpec { Type = "alphanumeric", Length = 11, UrlEncode = false, UpperCase = false },
        Headers = "Host: {host}\r\nAccept-Encoding: gzip\r\nUser-Agent: BitTornado/T-0.3.17\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&no_peer_id=1&compact=1{event}&key={key}",
        DefNumWant = 200, Parse = false, SearchString = "", ProcessName = "",
        StartOffset = 10000000, MaxOffset = 25000000,
      },

      // ===================== Burst =====================
      new ClientProfile {
        Family = "Burst", Version = "3.1.0b",
        HttpProtocol = "HTTP/1.0", HashUpperCase = true,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "Mbrst1-1-3",
        PeerIdRandom = new IdSpec { Type = "hex", Length = 10, UrlEncode = false, UpperCase = false },
        Headers = "Host: {host}\r\nAccept-Encoding: gzip\r\nUser-Agent: BitTorrent/brst1.1.3\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&key={key}&uploaded={uploaded}&downloaded={downloaded}&left={left}&compact=1{event}",
        DefNumWant = 200, Parse = false, SearchString = "", ProcessName = "",
        StartOffset = 10000000, MaxOffset = 25000000,
      },

      // ===================== BitTyrant =====================
      new ClientProfile {
        Family = "BitTyrant", Version = "1.1",
        HttpProtocol = "HTTP/1.1", HashUpperCase = true,
        Key = new IdSpec { Type = "alphanumeric", Length = 8, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "AZ2500BT",
        PeerIdRandom = new IdSpec { Type = "alphanumeric", Length = 12, UrlEncode = false, UpperCase = false },
        Headers = "User-Agent: AzureusBitTyrant 2.5.0.0BitTyrant;Windows XP;Java 1.5.0_10\n\rConnection: close\n\rAccept-Encoding: gzip\n\rHost: {host}\n\rAccept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2\n\rProxy-Connection: keep-alive\n\rContent-type: application/x-www-form-urlencoded\n\r",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&supportcrypto=1&port={port}&azudp={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}{event}&numwant={numwant}&no_peer_id=1&compact=1&key={key}",
        DefNumWant = 50, Parse = false, SearchString = "", ProcessName = "",
        StartOffset = 10000000, MaxOffset = 25000000,
      },

      // ===================== BitSpirit =====================
      new ClientProfile {
        Family = "BitSpirit", Version = "3.6.0.200",
        HttpProtocol = "HTTP/1.0", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "%2dSP3602",
        PeerIdRandom = new IdSpec { Type = "random", Length = 13, UrlEncode = true, UpperCase = false },
        Headers = "User-Agent: BTSP/3602\r\nHost: {host}\r\nAccept_Encoding: gzip\r\nConnection: close",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}{event}&key={key}&compact=1&numwant={numwant}&no_peer_id=1",
        DefNumWant = 200, Parse = false, SearchString = "", ProcessName = "",
        StartOffset = 10000000, MaxOffset = 25000000,
      },
      new ClientProfile {
        Family = "BitSpirit", Version = "3.1.0.077",
        HttpProtocol = "HTTP/1.0", HashUpperCase = false,
        Key = new IdSpec { Type = "numeric", Length = 3, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "%00%03BS",
        PeerIdRandom = new IdSpec { Type = "random", Length = 16, UrlEncode = true, UpperCase = false },
        Headers = "User-Agent: BitTorrent/4.1.2\r\nHost: {host}\r\nAccept-Encoding: gzip\r\nConnection: close",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}{event}&key={key}&compact=1&numwant={numwant}",
        DefNumWant = 200, Parse = false, SearchString = "", ProcessName = "",
        StartOffset = 10000000, MaxOffset = 25000000,
      },

      // ===================== Deluge =====================
      new ClientProfile {
        Family = "Deluge", Version = "2.1.1",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "alphanumeric", Length = 8, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "-DE2110-",
        PeerIdRandom = new IdSpec { Type = "alphanumeric", Length = 12, UrlEncode = false, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: Deluge/2.1.1 libtorrent/2.0.11.0\r\nAccept-Encoding: gzip\r\nConnection: close\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&corrupt=0&key={key}{event}&numwant={numwant}&compact=1&no_peer_id=1&supportcrypto=1&redundant=0",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-DE2110-", ProcessName = "deluge",
        StartOffset = 0, MaxOffset = 100000000,
      },
      new ClientProfile {
        Family = "Deluge", Version = "1.2.0",
        HttpProtocol = "HTTP/1.0", HashUpperCase = false,
        Key = new IdSpec { Type = "alphanumeric", Length = 8, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "-DE1200-",
        PeerIdRandom = new IdSpec { Type = "alphanumeric", Length = 12, UrlEncode = false, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: Deluge 1.2.0\r\nConnection: close\r\nAccept-Encoding: gzip\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&event={event}&key={key}&compact=1&numwant={numwant}&supportcrypto=1&no_peer_id=1",
        DefNumWant = 200, Parse = false, SearchString = "-DE1200-", ProcessName = "deluge",
        StartOffset = 0, MaxOffset = 100000000,
      },
      new ClientProfile {
        Family = "Deluge", Version = "0.5.8.7",
        HttpProtocol = "HTTP/1.0", HashUpperCase = false,
        Key = new IdSpec { Type = "alphanumeric", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-DE0587-",
        PeerIdRandom = new IdSpec { Type = "alphanumeric", Length = 12, UrlEncode = false, UpperCase = false },
        Headers = "Host: {host}\r\nAccept-Encoding: gzip\r\nUser-Agent: Deluge 0.5.8.7\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&event={event}&key={key}&compact=1&numwant={numwant}&supportcrypto=1&no_peer_id=1",
        DefNumWant = 200, Parse = false, SearchString = "-DE0587-", ProcessName = "deluge",
        StartOffset = 0, MaxOffset = 100000000,
      },
      new ClientProfile {
        Family = "Deluge", Version = "0.5.8.6",
        HttpProtocol = "HTTP/1.0", HashUpperCase = false,
        Key = new IdSpec { Type = "alphanumeric", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-DE0586-",
        PeerIdRandom = new IdSpec { Type = "alphanumeric", Length = 12, UrlEncode = false, UpperCase = false },
        Headers = "Host: {host}\r\nAccept-Encoding: gzip\r\nUser-Agent: Deluge 0.5.8.6\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&event={event}&key={key}&compact=1&numwant={numwant}&supportcrypto=1&no_peer_id=1",
        DefNumWant = 200, Parse = false, SearchString = "-DE0586-", ProcessName = "deluge",
        StartOffset = 0, MaxOffset = 100000000,
      },

      // ===================== KTorrent =====================
      new ClientProfile {
        Family = "KTorrent", Version = "2.2.1",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "numeric", Length = 10, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "-KT2210-",
        PeerIdRandom = new IdSpec { Type = "numeric", Length = 12, UrlEncode = false, UpperCase = false },
        Headers = "User-Agent: ktorrent/2.2.1\r\nAccept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2\r\nAccept-Encoding: x-gzip, x-deflate, gzip, deflate\r\nHost: {host}\r\nConnection: Keep-Alive\n\r",
        Query = "peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&compact=1&numwant={numwant}&key={key}{event}&info_hash={infohash}",
        DefNumWant = 100, Parse = false, SearchString = "", ProcessName = "",
        StartOffset = 10000000, MaxOffset = 25000000,
      },

      // ===================== Gnome BT =====================
      new ClientProfile {
        Family = "Gnome BT", Version = "0.0.28-1",
        HttpProtocol = "HTTP/1.1", HashUpperCase = true,
        Key = new IdSpec { Type = "alphanumeric", Length = 8, UrlEncode = false, UpperCase = false },
        PeerIdPrefix = "M3-4-2--",
        PeerIdRandom = new IdSpec { Type = "alphanumeric", Length = 12, UrlEncode = false, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: Python-urllib/2.5\r\nConnection: close\r\nAccept-Encoding: gzip",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&key={key}&uploaded={uploaded}&downloaded={downloaded}&left={left}&compact=1{event}",
        DefNumWant = 100, Parse = false, SearchString = "", ProcessName = "",
        StartOffset = 10000000, MaxOffset = 25000000,
      },

      // ===================== libtorrent (modern) =====================
      new ClientProfile {
        Family = "libtorrent", Version = "2.1.0",
        HttpProtocol = "HTTP/1.1", HashUpperCase = false,
        Key = new IdSpec { Type = "hex", Length = 8, UrlEncode = false, UpperCase = true },
        PeerIdPrefix = "-LT2100-",
        PeerIdRandom = new IdSpec { Type = "random", Length = 12, UrlEncode = true, UpperCase = false },
        Headers = "Host: {host}\r\nUser-Agent: libtorrent/2.1.0\r\nAccept-Encoding: gzip\r\nConnection: close\r\n",
        Query = "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&corrupt=0&key={key}{event}&numwant={numwant}&compact=1&no_peer_id=1&supportcrypto=1&redundant=0",
        DefNumWant = 200, Parse = true, SearchString = "&peer_id=-LT2100-", ProcessName = "libtorrent",
        StartOffset = 0, MaxOffset = 100000000,
      },
    };
  }
}
